services:
    davidiq.phpbbasic.listener:
        class: davidiq\phpbbasic\event\listener
        arguments:
            - @config
            - @request
            - @service_container
            - @dbal.conn
            - @user
            - @auth
            - @template
            - @cache
            - @dispatcher
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
