services:
    davidiq.phpbbasic.listener:
        class: davidiq\phpbbasic\event\listener
        arguments:
            - '@config'
            - '@request'
            - '@cron.manager'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@template'
            - '@cache'
            - '@dispatcher'
            - '@path_helper'
            - '@pagination'
            - '@content.visibility'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
