services:
    davidiq.phpbbasic.listener:
        class: davidiq\phpbbasic\event\listener
        arguments:
            - @config
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
